App_Login/urls.py
from django import views
from django.urls import URLPattern, path
from App_Login import views
app_name='App_Login'

urlpatterns = [
    path('signup/',views.sign_up,name='sign_up'),
    path('login/',views.login_user,name='login'),
    path('edit/',views.edit_profile,name='edit'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('user/<username>/',views.user,name='user'),
    path('follow/<username>/',views.follow,name='follow'),
    path('unfollow/<username>/',views.unfollow,name='unfollow'),
    

]

App_Post/urls.py
from importlib.resources import path
from django.urls import URLPattern,path
from App_Post import views

app_name='App_Post'

urlpatterns=[
    path('',views.home,name='home'),
    path('liked/<pk>/',views.liked,name='liked'),
    path('unliked/<pk>/',views.unliked,name='unliked'),

]

Social_Media_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from App_Post import views
from App_Post import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('App_Login.urls')),
    path('post/',include('App_Post.urls')),
    path('',views.home,),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from pyexpat import model
from re import M
from turtle import mode
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,
    related_name='user_profile')
    profile_pic=models.ImageField(upload_to='profile_pics', blank=True)
    description=models.TextField(blank=True)
    full_name=models.CharField(max_length=264,blank=True)
    dob=models.DateField(blank=True,null=True)
    website=models.URLField(blank=True)
    facebook=models.URLField(blank=True)

class Follow(models.Model):
    follower=models.ForeignKey(User,on_delete=models.CASCADE,
    related_name='follower')
    following=models.ForeignKey(User,on_delete=models.CASCADE,
    related_name='following')
    created_at=models.DateTimeField(auto_now_add=True)
    

App_Login/forms.py
from dataclasses import fields
from pyexpat import model
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from App_Login.models import UserProfile
class CreateNewUser(UserCreationForm):
    email=forms.EmailField(required=True,label="",
    widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username=forms.CharField(required=True,label="",
    widget=forms.TextInput(attrs={'placeholder':'username'}))
    password1=forms.CharField(
        required=True,
        label="",
        widget=forms.PasswordInput(attrs={'placeholder':'password'})
    )
    password2=forms.CharField(
        required=True,
        label="",
        widget=forms.PasswordInput(attrs={'placeholder':'password'})
    )
    class Meta:
        model=User
        fields=('email','username','password1','password2')

class EditProfile(forms.ModelForm):
    dob=forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:        
        model=UserProfile
        fields=('profile_pic','full_name','description','dob','website','facebook')

App_Login/views.py
from multiprocessing import context
from multiprocessing.dummy import current_process
from urllib.request import Request
from django.shortcuts import render,HttpResponseRedirect
from App_Login.forms import *
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse,reverse_lazy
from App_Login.models import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from App_Post.forms import *
from App_Post.models import *
from django.contrib.auth.models import User


# Create your views here.
def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method=='POST':
        form=CreateNewUser(data=request.POST)
        if form.is_valid():
            user=form.save()
            registered=True
            user_profile=UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('App_Login:login'))
    context={
        'title':'Signup.Instagram',
        'form':form
    }

    return render(request,'App_Login/sign_up.html',context)

def login_user(request):
    form=AuthenticationForm()
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            user=authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('App_Post:home'))

    context={
        'title':login,
        'form':form
    }
    return render(request,'APP_Login/login.html',context)

@login_required
def edit_profile(request):
    current_user=UserProfile.objects.get(user=request.user)
    form=EditProfile(instance=current_user)
    if request.method=='POST':
        form=EditProfile(request.POST,request.FILES,instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form=EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('App_Login:profile'))
    context={
        'title':'Edit Profile Social',
        'form':form
    }
    return render(request,'App_Login/Edit_Profile.html',context)

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:login'))


@login_required
def profile(request):
    form=PostForm()
    if request.method=='POST':
        form=PostForm(request.POST,request.FILES)
        if form.is_valid():
            post=form.save(commit=False)
            post.author=request.user
            post.save()
            return HttpResponseRedirect(reverse('App_Post:home'))

    context={
        'title':' User Profile',
        'form':form,

    }
    return render(request,'App_Login/user.html',context)

@login_required
def user(request,username):
    user_other=User.objects.get(username=username)
    already_followed=Follow.objects.filter(follower=request.user,following=user_other)
    if user_other==request.user:
        return HttpResponseRedirect(reverse('App_Login:profile'))
    context={
        'user_other':user_other,
        'already_followed':already_followed,
    }
    return render(request,'App_Login/user_other.html',context)


@login_required
def follow(request,username):
    following_user=User.objects.get(username=username)
    follower_user=request.user
    already_followed=Follow.objects.filter(follower=follower_user,following=following_user)
    if not already_followed:
        followed_user=Follow(follower=follower_user,following=following_user)
        followed_user.save()
    return HttpResponseRedirect(reverse('App_Login:user',kwargs={'username':username}))

@login_required
def unfollow(request,username):
    following_user=User.objects.get(username=username)
    follower_user=request.user
    already_followed=Follow.objects.filter(follower=follower_user,following=following_user)
    already_followed.delete()
    return HttpResponseRedirect(reverse('App_Login:user',kwargs={'username':username}))

templates/App_Login/Edit_Profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{ title }}
{% endblock %}

{% block body_block %}
<form action="" method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" name="button" class="btn btn-primary">Submit</button>
</form>
{% endblock%}

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{ title }} {% endblock %}
{% block css_block %}
<style>

    .login{
        width: 550px;
        border: 1px solid #ccc;
        padding: 40px;
    }
    .signup{
    width: 550px;
    border: 1px solid #ccc;
    padding-top: 5px;

}
</style>
{% endblock %}
{% block body_block %}
<center>
<div class="login">   
<form action="" method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" style="width: 100%;" class="btn btn-primary">Log in</button>
</form>
</div>
<br>
<div class="signup">
    <p>Have an Account?<a href="{% url 'App_Login:sign_up' %}">Sign Up</a></p>
</div>
</center>



{% endblock %}

templates/App_Login/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{ title }} {% endblock %}

{% block css_block %}
<style>

.sign_up{
    width: 550px;
    border: 1px solid #ccc;
    padding: 40px;
}
.log_in{
    width: 550px;
    border: 1px solid #ccc;
    padding-top: 5px;

}

</style>
{% endblock %}
{% block body_block %}
<center>
<div class="sign_up">
    <h3>Sign Up to See Photos From Your Friends</h3>
<form action="" method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" style="width: 100%;" class="btn btn-primary">Sign Up</button>
</form>
</div>
<br>
<div class="log_in">
<p>Have an Account?<a href="{% url 'App_Login:login' %}">Log in</a></p>
</div>
</center>
{% endblock %}

templates/App_Login/user.html
{% extends 'navbar.html' %}
{% block title_block %} {{ user.user_profile.full_name}} (@{{user.username}})
{% endblock %}

{% block css_block %}
<style>
.crop{
  width: 200px;
  height: 200px;
  overflow: hidden;
}
.crop img{
  width: 400px;
  height: 600px;
  margin: -75px 0 0 -100px;
  padding: 10px;
}

</style>
{% endblock %}

{% block body_block %}
<div class="row">
    <div class="col-sm-4">
        {% if user.user_profile.profile_pic %}
        <a class="nav-link">
         <img src="/media/{{ user.user_profile.profile_pic }}" width="200px" height="320px"  alt=""  style="border-radius: 50%;">
        </a>
      
      {% else %}
      <a class="nav-link ">
        <img src="/static/img/default.png" width="200px" height="200px"  alt="" style="border-radius: 50%;">
      </a>
      
      {% endif %}
    </div>
    <div class="col-sm-8">
    <h3>{{ user.username }} &nbsp; <a href="{% url 'App_Login:edit' %}" class="btn btn-light">Edit Profile</a></h3>
    <h4>{{user.post.count}} posts &nbsp; {{ user.following.count }} followers &nbsp; {{ user.follower.count }}following</h4>
    <br>
    <h4>{{ user.user_profile.full_name}}</h4>
    <h4>{{ user.user_profile.description|linebreaks }}</h4>
    <br>
  </div>
</div>
  <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Add Post
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Post a Photo</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST" enctype="multipart/form-data">
          {{form.as_p}}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary">Post</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>        
      </div>
    </div>
  </div>
</div>
<br>
<!-- Get Post -->
<div class="row">
  {% for post in user.post.all  %}
  <div class="crop">
<img src="/media/{{post.image}}">
<br> {{ post.caption }} &nbsp; &nbsp;
</div>
<br><br>
  {% endfor %}
</div>

{% endblock %}

templates/App_Login/user_other.html
{% extends 'navbar.html' %}
{% block title_block %} {{ user_other.user_profile.full_name}} (@{{user_other.username}})
{% endblock %}

{% block css_block %}
<style>
.crop{
  width: 200px;
  height: 200px;
  overflow: hidden;
}
c.crop img{
  width: 400px;
  height: 300px;
  margin: -75px 0 0 -100px;
}

</style>
{% endblock %}

{% block body_block %}
<div class="row">
    <div class="col-sm-4">
        {% if user_other.user_profile.profile_pic %}
        <a class="nav-link">
         <img src="/media/{{ user_other.user_profile.profile_pic }}" width="200px" height="320px"  alt=""  style="border-radius: 50%;">
        </a>
      
      {% else %}
      <a class="nav-link ">
        <img src="/static/img/default.png" width="200px" height="200px"  alt="" style="border-radius: 50%;">
      </a> 
      {% endif %}
    </div>
    <div class="col-sm-8">      
        {% if not already_followed %}
        <h1>{{user_other.username}} &nbsp; <a href="{% url 'App_Login:follow' username=user_other.username %}" class="btn btn-primary">Follow</a></h1>
        {% else %}
        <h1>{{user_other.username}} &nbsp; <a href="{% url 'App_Login:unfollow' username=user_other.username %}" class="btn btn-primary">Unfollow</a></h1>
        {% endif %}
        <h4>{{user_other.post.count}} posts &nbsp; {{ user_other.following.count }} followers &nbsp; {{ user_other.follower.count }}following</h4>
    <br>
    <h4>{{ user_other.user_profile.full_name}}</h4>
    <h4>{{ user_other.user_profile.description|linebreaks }}</h4>
    <br>
  </div>
</div>
<!-- Get Post -->
<div class="row">
  {% for post in user.post.all  %}
  <div class="crop">
<img src="/media/{{post.image}}" title="{{ post.caption }}">
</div>
<br><br>
  {% endfor %}
</div>

{% endblock %}