App_Login/urls.py
from django import views
from django.urls import URLPattern, path
from App_Login import views
app_name='App_Login'

urlpatterns = [
    path('signup/',views.sign_up,name='sign_up'),
    path('login/',views.login_user,name='login'),
    path('edit/',views.edit_profile,name='edit'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('user/<username>/',views.user,name='user'),
    path('follow/<username>/',views.follow,name='follow'),
    path('unfollow/<username>/',views.unfollow,name='unfollow'),
    

]

App_Post/urls.py
from importlib.resources import path
from django.urls import URLPattern,path
from App_Post import views

app_name='App_Post'

urlpatterns=[
    path('',views.home,name='home'),
    path('liked/<pk>/',views.liked,name='liked'),
    path('unliked/<pk>/',views.unliked,name='unliked'),

]

Social_Media_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from App_Post import views
from App_Post import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('App_Login.urls')),
    path('post/',include('App_Post.urls')),
    path('',views.home,),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Post/models.py
from email.mime import image
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='post')
    image=models.ImageField(upload_to='post_images')
    caption=models.CharField(max_length=264,blank=True)
    upload_date=models.DateField(auto_now_add=True)
    upload_date=models.DateField(auto_now=True)
    class Meta:
        ordering=['-upload_date',]

class Like(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='liked_post')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='liker')
    date_created=models.DateField(auto_now_add=True)

    def __str__(self):
        return '{}:{}'.format(self.user,self.post)

App_Post/forms.py
from dataclasses import fields
from pyexpat import model
from django import forms
from App_Post.models import Post
class PostForm(forms.ModelForm):

    class Meta:
        model=Post
        fields=['image','caption']

App_Post/views.py
from multiprocessing import context
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse
from App_Login.views import user
from .models import *
from App_Login.models import Follow
# Create your views here.
@login_required
def home(request):
    following_list=Follow.objects.filter(follower=request.user)
    posts=Post.objects.filter(author__in=following_list.values_list('following'))
    liked_post=Like.objects.filter(user=request.user)
    liked_post_list=liked_post.values_list('post',flat=True)
    if request.method=='GET':
        search=request.GET.get('search','')
        result=User.objects.filter(username__icontains=search)
    context={
        'title':'home',
        'search':search,
        'result':result,
        'following_list':following_list,
        'posts':posts,
        'liked_post_list':liked_post_list
    }
    return render(request,'APP_Post/home.html',context)

@login_required
def liked(request,pk):
    post=Post.objects.get(pk=pk)
    already_liked=Like.objects.filter(post=post,user=request.user)
    if not already_liked:
        liked_post=Like(post=post,user=request.user)
        liked_post.save()
    return HttpResponseRedirect(reverse('App_Post:home'))

@login_required
def unliked(request,pk):
    post=Post.objects.get(pk=pk)
    already_liked=Like.objects.filter(post=post,user=request.user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('App_Post:home'))

templates/App_Post/home.html
{% extends 'navbar.html' %}
{% block title_block %}
{% endblock %}

{% block body_block %}
{% if search %}
{% for user in result %}
<div class="row">
<div class="col-sm-1">
    {% if user.user_profile.profile_pic %}
<img src="/media/{{ user.user_profile.profile_pic }}" 
      width="50px" height="50px"  alt=""  style="border-radius: 50%;">
  
  {% else %}
    <img src="/static/img/default.png" width="50px" height="50px"  alt="" style="border-radius: 50%;">
{% endif %}
</div>
<div class="col-sm-10">
    <a href="{% url 'App_Login:user' username=user.username %}">{{user.username}} </a>
    <br>
    {{user.user_profile.full_name}}
</div></div>

{% endfor %}

{% else %}
<div class="row">
    <div class="col-sm-8">
{% for post in posts %}

<div style="border: 1px solid #888888;">
    <div style="padding: 10px;">
   
    {% if post.author.user.user_profile.profile_pic %}
<img src="/media/{{ user.user_profile.profile_pic }}" 
      width="40px" height="40px"  alt=""  style="border-radius: 50%;">
  
  {% else %}
  <img src="/static/img/default.png" width="40px" height="40px"  alt="" style="border-radius: 50%;">
  {% endif %}
  <a href="{% url 'App_Login:user' username=post.author %}"></a>{{ post.author }}
  </div>
      <img src="/media/{{post.image}}" width="100%">
      <div style="padding: 20px;">
        
        {% if post.pk in liked_post_list%}
         <a href="{% url 'App_Post:unliked' pk=post.pk %}"> <i class="fa fa-heart" style="font-size: 36px;"></i></a>
        {% else %}
        <a href="{% url 'App_Post:liked' pk=post.pk %}"><i class="fa fa-heart-o" style="font-size: 36px;"></i></a>
        {% endif %} &nbsp;
        <b>{{post.liked_post.count}} Likes</b>
        <br>
        {{post.caption}} <br>
      </div>
  </div>
  <br><br>
  {% endfor %}
</div>


<div class="col-sm-4">
    <div class="row">
        <div class="col-sm-4">
            {% if user.user_profile.profile_pic %}
            <img src="/media/{{ user.user_profile.profile_pic }}" 
                  width="50px" height="50px"  alt=""  style="border-radius: 50%;">
              
              {% else %}
                <img src="/static/img/default.png" width="50px" height="50px"  alt="" style="border-radius: 50%;">
            {% endif %}
            <div class="col-sm-8">
                {{user.user_profile.full_name}}
            </div>
        </div>
    </div>
   
</div>
</div>
  

{% endif %}
{% endblock %}